# Generated by Django 4.1.7 on 2023-04-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_emp_comn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='comn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
